#!/usr/bin/sh

# Author: Yukal Alexander <yukal@email.ua>
# License MIT
# Version: 1.0

APPNAME="btrx_clnt"
WORKDIR="/app"
#IMAGE="node:10-alpine"
IMAGE="node:10"
PORT_EXT=8080 #External
PORT_INN=8080 #Internal
PORTS="$PORT_EXT:$PORT_INN"
SCRIPT_NAME=$(basename $0)
SCRIPT=$WORKDIR/$SCRIPT_NAME

MSG_TITLE() { printf "\n#\e[32m $1 ...\e[m\n# ========================\n"; }
MSG_ERROR() { printf "\e[31m${1}\e[m\n"; }
PKG_EXISTS() { if `which "$1" >/dev/null 2>&1`; then return 0; else return 1; fi }
REQUIRED() {
    if ! PKG_EXISTS "$1"; then
        MSG_ERROR "$1 requred! Please install it first"
        exit 1
    fi
}

if [ -z "$1" ]; 
    then PARAMS="sh $SCRIPT";
    else PARAMS="$1";
fi

if [ ! -f /.dockerenv ]; then
    # Host environment entry

    REQUIRED "docker";

    # Start project
    MSG_TITLE "Init from $IMAGE"
    docker run -it --rm --name $APPNAME -u "$UID:$GROUPS" -p "$PORTS" -v "$PWD":"$WORKDIR" -w "$WORKDIR" $IMAGE $PARAMS
    exit 0

else
    # Virtual environment entry

    REQUIRED "node";
    REQUIRED "npm";

    # Install dependencies
    if [ ! -d "$WORKDIR/node_modules" ]; then
        MSG_TITLE "Installing project dependencies"
        npm install
    fi

    # Fix owner
    # chown -R $UID:$GID $WORKDIR

    MSG_TITLE "Start Server"
    npm run server
fi

exit 0
