version: '3.3'

services:
  server:
    container_name: bitrix_srv
    image: node:10
    working_dir: /app
    expose:
      - '8181'
    volumes:
      - ./server:/app
    command: ['npm','run','serve']

  client:
    container_name: bitrix_clnt
    image: node:10
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    command: ['npm','run','serve']
    depends_on:
      - server
